name: iOS Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Capacitor Sync
        run: npx cap sync ios

      - name: Build Xcode Project
        run: |
          xcodebuild -workspace ios/App/App.xcworkspace \
                     -scheme App \
                     -sdk iphoneos \
                     -configuration Debug \
                     CODE_SIGNING_ALLOWED=NO | xcpretty
